account/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v
urlpatterns = [
    path('register', v.register,name='register'),
    path('login', v.login_view,name='login'),
    path('logout', v.logout_view,name='logout'),
]

online_shoping/urls.py
from account import views as v
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home),
    path('product-',include(('product.urls','product'),namespace="product")),
    path('account-',include(('account.urls','account'),namespace="account")),
    path('order-',include(('orderapp.urls','orderapp'),namespace="orderapp")),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orderapp/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v
urlpatterns = [
    path('addcart/<int:id>', v.addtocart,name='addcart'),
]

product/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v
urlpatterns = [
    path('category/<int:id>/',v.get_by_category,name="get_by_category"),
    path('search',v.search_product,name="search"),
]

account/models.py
from django.db import models

from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm

class UserInfo(User):
    age=models.IntegerField()
    contact=models.CharField(max_length=30)
    gender=models.CharField(max_length=10)


from django import forms

class UserForm(UserCreationForm):
    class Meta:
        model=UserInfo
        fields=['username','first_name','last_name','age','contact','email','gender','password1','password2']

class LoginForm(forms.Form):
    UserName=forms.CharField(max_length=30)
    Password=forms.CharField(max_length=30,widget=forms.PasswordInput)

orderapp/models.py
from django.db import models
from product.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

product/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=30)
    description=models.TextField(max_length=300)

    def __str__(s):
        return s.name

class Product(models.Model):
    name=models.CharField(max_length=30)
    price=models.IntegerField()
    description=models.TextField(max_length=300)
    img=models.ImageField(upload_to="images",default="")
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(s):
        return s.name

account/views.py
from django.shortcuts import render,redirect,HttpResponse
from product.models import Category,Product
from .models import User,UserForm,UserInfo,LoginForm
from django.contrib.auth import login,logout,authenticate

def home(request):
    cl=Category.objects.all()
    pl=Product.objects.all()
    d={'cl':cl,'pl':pl}
    return render(request,'home.html',d)


def register(request):
    cl=Category.objects.all()
    pl=Product.objects.all()

    if request.method=='POST':
        f=UserForm(request.POST)
        f.save()
        return redirect('/')
    else:
        f=UserForm
        d={'pl':pl,'cl':cl,'form':f}
        return render(request,'form.html',d)

def login_view(request):
    cl=Category.objects.all()
    pl=Product.objects.all()

    if request.method=='POST':
        uname=request.POST.get('UserName')
        passw=request.POST.get('Password')
        user=authenticate(request,username=uname,password=passw)
        if user is not None:
            request.session['uid']=user.id
            login(request,user) 
            return redirect('/')
        else:
            return HttpResponse('<h1>InValid UserName and Password</h1>')
    else:
        f=LoginForm
        d={'pl':pl,'cl':cl,'form':f}
        return render(request,'form.html',d)

def logout_view(request):
    logout(request)
    return redirect('/')

orderapp/views.py
from django.shortcuts import render,redirect
from .models import Cart,Product,User

def addtocart(request,id):
    uid=request.session.get('uid')
    c=Cart()
    product=Product.objects.get(id=id)
    user=User.objects.get(id=uid)
    c.product=product
    c.user=user
    c.save()
    return redirect('/')

product/views.py
from django.shortcuts import render,redirect
from .models import Category,Product
def get_by_category(request,id):
    cl=Category.objects.all()
    pl=Product.objects.filter(category=id)
    d={'cl':cl,'pl':pl}
    return render(request,'home.html',d)


def search_product(request):
    cl=Category.objects.all()
    if request.method=='POST':
        srch=request.POST.get('srch')
        pl=Product.objects.filter(name__contains=srch)
        d={'cl':cl,'pl':pl}
        return render(request,'search.html',d)
    else:
        pl=Product.objects.all()
        d={'cl':cl,'pl':pl}
        return render(request,'search.html',d)

account/templates/form.html
{%extends 'base.html'%} {%block Data%}

<form method="POST">
    {%csrf_token%}

    <table>
        {{form.as_table}}

        <tr>
            <td><input type="submit" value="Submit"></td>
            <td><input type="reset" value="Reset"></td>
        </tr>
    </table>

</form>
{%endblock%}

account/templates/home.html
{%extends 'base.html'%} {%block Data%} {%for i in pl%}
<div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{{i.img}}" alt=""></a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">{{i.name}}</a>
            </h4>
            <h5>{{i.price}}&nbsp; &#x20B9</h5>
            {%if user.is_authenticated%}
            <h5><button><a style="text-decoration: none;" href="{%url 'orderapp:addcart' i.id %}">addToCart</a></button></h5>
            {%else%}
            <h5><button><a style="text-decoration: none;" href="{%url 'account:login' %}">addToCart</a></button></h5>
            {%endif%}
            <p class="card-text">{{i.description}}</p>
        </div>
        <div class="card-footer">
            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
        </div>
    </div>
</div>

{%endfor%} {%endblock%}

product/templates/search.html
{%extends 'base1.html'%} {% block search%}
<br>
<form method="POST">
    {%csrf_token%}
    <textarea cols="80" rows="3" name="srch"></textarea>
    <input type="submit" value="SEARCH">
</form>
<br>
<br> {%endblock%}
<br> {%block Data%} {%for i in pl%}
<div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{{i.img}}" alt=""></a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">{{i.name}}</a>
            </h4>
            <h5>{{i.price}}&nbsp; &#x20B9</h5>
            <p class="card-text">{{i.description}}</p>
        </div>
        <div class="card-footer">
            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
        </div>
    </div>
</div>

{%endfor%} {%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    {%load static%}
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bmin.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static 'css/myapp.css'%}" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    {%include 'navbar.html'%}

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- SideBAr-->
            {%include 'sidebar.html'%}
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <!--Slider-->
                {%include 'slider.html'%}

                <div class="row">

                    <!--Body-->

                    {%block Data%} {%endblock%}
                </div>
                <!-- /.row -->

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    {%include 'footer.html'%}

    <!-- Bootstrap core JavaScript -->
    <script src="{%static 'js/jq.js'%}"></script>
    <script src="{%static 'js/bst.js'%}"></script>

</body>

</html>

templates/base1.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    {%load static%}
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bmin.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static 'css/myapp.css'%}" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    {%include 'navbar.html'%}

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- SideBAr-->
            {%include 'sidebar.html'%}
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <!--Slider-->
                {%block search%} {%endblock%}

                <div class="row">

                    <!--Body-->

                    {%block Data%} {%endblock%}
                </div>
                <!-- /.row -->

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    {%include 'footer.html'%}

    <!-- Bootstrap core JavaScript -->
    <script src="{%static 'js/jq.js'%}"></script>
    <script src="{%static 'js/bst.js'%}"></script>
</body>

</html>

templates/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">WELCOME {{user.first_name}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home
          <span class="sr-only">(current)</span>
        </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'product:search' %}">Search</a>
                </li>


                {%if user.is_authenticated%}
                <li class="nav-item">
                    <a class="nav-link" href="/">CartList</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/">MyOrder</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'account:logout' %}">Logout</a>
                </li>
                {%else%}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'account:register' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{%url 'account:login' %}">Login</a>
                </li>

                {%endif%}


                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/sidebar.html
<div class="col-lg-3">

    <h1 class="my-4">Shop Name</h1>
    <div class="list-group">
        {%for i in cl%}
        <a href="{%url 'product:get_by_category' i.id%}" class="list-group-item">{{i.name}}</a> {%endfor%}
    </div>

</div>

templates/slider.html
{%load static%}
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="{%static 'images/slider.jpg'%}" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>